before_script:
  - source $HOME/deploy_configuration/configure.sh

stages:
  - test
  - publish

test:
  stage: test
  tags:
    - analysts
  script:
    - sbt clean update test
  only:
    - master

publish:
  stage: publish
  tags:
    - analysts
  script:
    - sbt clean update package publish
  environment:
    name: production
  only:
    - master
 
